### ISSUE TITLE
Windows Defender flags the release version as a virus

### ISSUE THREAD

**Issue by LorenDB** [wiera987/PDFComp#2]
I tried to download the release on a Windows PC, but Windows Defender flagged it as a virus. [According to VirusTotal](https://www.virustotal.com/gui/url/fe2994ed6d3b829490cdfdd57e32ea36002ba65949909cbf745ae69e5e352136), no other vendor flags the file as a virus, so I suspect Defender is likely hitting a false positive. Still, I thought I'd mention it here so you can be aware of the problem.

**Comment by wiera987** [comment]
Thank you for reporting this.
Please check the latest definition file to see if this has been resolved.

I just checked with the Microsoft Defender definition file
 1.421.771.0 (2024/12/13 13:17) on  Windows 11,
and there were no warnings when downloading with Edge.
I scanned the downloaded file with Microsoft Defender and found no threats.

**Comment by LorenDB** [comment]
Yup, works with latest updates now.
